### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by youchen-0** [zhiguai/CZ-LoveCards#2]
1. 发信接口......我感觉群里公告说的好复杂的样子.用phpmailer,通过各大邮箱平台的smtp发送有什么问题吗?
2. 希望验证码支持更换为hcaptcha和recaptcha
3. https://matomo.fatda.cn/matomo.js 严重拖慢网站打开速度,建议把这个文件放到服务器源码里,或者干脆直接用cdn代替,https://cdn.jsdelivr.net/gh/matomo-org/matomo@4.x-dev/js/piwik.min.js
4. github star数量完全不能表现使用人数,毕竟多数人(甚至包括不少站长)是不知道github的.像被倒卖无数次的duckchat在github上只有不到80个star

**Comment by youchen-0** [comment]
发邮件也可以不用phpmailer,php也可以直接发信的
[相关文章](https://blog.csdn.net/weixin_39654436/article/details/115205011)

**Comment by zhiguai** [comment]
非常感谢，该项目暂时处于停止维护的状态，后期如有时间会修复当前漏洞。
